#!/bin/bash






# -------- DECLARATIONS --------

#exit on error
set -e

#current execution directory
CXD=$(dirname $(realpath $0))
pCXD=$(dirname $CXD)

#output dirs
OUT_APP=$pCXD/out/app
OUT_TMP=$pCXD/out/tmp






# -------- EXECUTION --------

#purge
$pCXD/bld/purge

#prepare output dirs
mkdir --parents $OUT_TMP $OUT_APP

#work in tmp dir
cd $OUT_TMP

#build app
echo "Compilation..."
echo "    NO COMPILATION PROCESS FOR THE MOMENT"

#end message
echo "Done."
